<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'LammCore\Module'                          => __DIR__ . '/Module.php',
  'LammCore\Common\Enum'                     => __DIR__ . '/src/LammCore/Common/Enum.php',
  'LammCore\ConfigAwareInterface'            => __DIR__ . '/src/LammCore/ConfigAwareInterface.php',
  'LammCore\Controller\IndexController'      => __DIR__ . '/src/LammCore/Controller/IndexController.php',
  'LammCore\Db\Sql\Select'                   => __DIR__ . '/src/LammCore/Db/Sql/Select.php',
  'LammCore\Db\Sql\Sql'                      => __DIR__ . '/src/LammCore/Db/Sql/Sql.php',
  'LammCore\Filter\Minify'                   => __DIR__ . '/src/LammCore/Filter/Minify.php',
  'LammCore\Model\AbstractModel'             => __DIR__ . '/src/LammCore/Model/AbstractModel.php',
  'LammCore\Mvc\Controller\ActionController' => __DIR__ . '/src/LammCore/Mvc/Controller/ActionController.php',
  'LammCore\Stdlib\ArrayUtils'               => __DIR__ . '/src/LammCore/Stdlib/ArrayUtils.php',
  'LammCore\Stdlib\Solr'                     => __DIR__ . '/src/LammCore/Stdlib/Solr.php',
  'LammCore\Test\Framework\TestCase'         => __DIR__ . '/tests/LammCore/Framework/TestCase.php',
  'LammCore\Test\SampleTest'                 => __DIR__ . '/tests/LammCore/SampleTest.php',
);
