<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LammCoreTest\Framework\TestCase'     => __DIR__ . '/tests/LammCore/Framework/TestCase.php',
    'LammCoreTest\SampleTest'             => __DIR__ . '/tests/LammCore/SampleTest.php',
    'LammCore\Controller\IndexController' => __DIR__ . '/src/LammCore/Controller/IndexController.php',
    'LammCore\Common\Enum'                => __DIR__ . '/src/LammCore/Common/Enum.php',
    'LammCore\Module'                     => __DIR__ . '/Module.php',
);
